language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install

before_script:
  - psql -c 'create database ridemyway;' -U postgres

# command to run tests
script:
  - sh run_test.sh

notifications:
    slack: andela:CZMPqh8lpJiFzgTKBVdzOREr