language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - cd server
  - python3 manage.py test tests -v 2 # or py.test for Python versions 3.5 and below

notifications:
    slack: andela:CZMPqh8lpJiFzgTKBVdzOREr