language: python
python:
  - "3.6"
services:
  - postgresql
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install

before_script:
  - cd server

# command to run tests
script:
  - python3 manage.py test tests -v 2

notifications:
    slack: andela:CZMPqh8lpJiFzgTKBVdzOREr