# Generated by Django 2.0.6 on 2018-06-27 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRides',
            fields=[
                ('offer_id', models.CharField(blank=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('pick_up', models.TextField(max_length=255)),
                ('take_off_time', models.DateTimeField()),
                ('destination', models.TextField()),
                ('available_space', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-offer_id'],
            },
        ),
        migrations.CreateModel(
            name='RequestRides',
            fields=[
                ('request_id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestrides', to=settings.AUTH_USER_MODEL)),
                ('rides', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerrides', to='ridemywayapp.OfferRides')),
            ],
            options={
                'ordering': ['-request_id'],
            },
        ),
    ]
