# Generated by Django 2.0.6 on 2018-06-27 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrides',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestrides',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestrides',
            name='rides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestrides', to='ridemywayapp.OfferRides'),
        ),
    ]
