# Generated by Django 2.0.6 on 2018-07-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrides',
            name='available_space',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
