# Generated by Django 2.0.6 on 2018-06-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0002_auto_20180620_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
