# Generated by Django 2.0.6 on 2018-06-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0002_auto_20180627_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestrides',
            old_name='rides',
            new_name='offerrides',
        ),
    ]
