# Generated by Django 2.0.6 on 2018-06-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0004_auto_20180620_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
