# Generated by Django 2.0.6 on 2018-06-21 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridemywayapp', '0007_auto_20180621_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('ride_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pick_up', models.TextField(max_length=255)),
                ('take_off_time', models.DateTimeField()),
                ('destination', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ride_id'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='rides',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
