# Generated by Django 2.0.6 on 2018-06-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0010_auto_20180622_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='rider',
            new_name='user',
        ),
    ]
