# Generated by Django 2.0.6 on 2018-06-25 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridemywayapp', '0011_auto_20180624_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRides',
            fields=[
                ('offer_id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-offer_id'],
            },
        ),
        migrations.AddField(
            model_name='rides',
            name='available_space',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offerrides',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rides', to='ridemywayapp.Rides'),
        ),
        migrations.AddField(
            model_name='offerrides',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
