# Generated by Django 2.0.6 on 2018-06-25 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ridemywayapp', '0012_auto_20180625_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferRides',
            new_name='RequestRides',
        ),
        migrations.AlterModelOptions(
            name='requestrides',
            options={'ordering': ['-request_id']},
        ),
        migrations.RenameField(
            model_name='requestrides',
            old_name='offer_id',
            new_name='request_id',
        ),
    ]
