# Generated by Django 2.0.6 on 2018-06-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridemywayapp', '0014_auto_20180625_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerrides',
            options={'ordering': ['-offer_id']},
        ),
        migrations.RenameField(
            model_name='offerrides',
            old_name='ride_id',
            new_name='offer_id',
        ),
        migrations.RenameField(
            model_name='requestrides',
            old_name='ride',
            new_name='offer',
        ),
    ]
